/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'apps-categories-list': RouteRecordInfo<'apps-categories-list', '/apps/categories/list', Record<never, never>, Record<never, never>>,
    'apps-client-components-clientmodal': RouteRecordInfo<'apps-client-components-clientmodal', '/apps/client/components/clientmodal', Record<never, never>, Record<never, never>>,
    'apps-client-components-contactclientmodal': RouteRecordInfo<'apps-client-components-contactclientmodal', '/apps/client/components/contactclientmodal', Record<never, never>, Record<never, never>>,
    'apps-client-list': RouteRecordInfo<'apps-client-list', '/apps/client/list', Record<never, never>, Record<never, never>>,
    'apps-client-view-id': RouteRecordInfo<'apps-client-view-id', '/apps/client/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-domain-list': RouteRecordInfo<'apps-domain-list', '/apps/domain/list', Record<never, never>, Record<never, never>>,
    'apps-user-list': RouteRecordInfo<'apps-user-list', '/apps/user/list', Record<never, never>, Record<never, never>>,
    'apps-user-view-id': RouteRecordInfo<'apps-user-view-id', '/apps/user/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
  }
}
